# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1006, 743)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/book.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tree = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree.sizePolicy().hasHeightForWidth())
        self.tree.setSizePolicy(sizePolicy)
        self.tree.setObjectName("tree")
        self.gridLayout.addWidget(self.tree, 0, 0, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.page_view = QtWidgets.QWidget()
        self.page_view.setGeometry(QtCore.QRect(0, 0, 721, 610))
        self.page_view.setObjectName("page_view")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_view)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_view)
        self.textBrowser.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_view, "")
        self.page_edit = QtWidgets.QWidget()
        self.page_edit.setGeometry(QtCore.QRect(0, 0, 154, 166))
        self.page_edit.setObjectName("page_edit")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_edit)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page_edit)
        self.plainTextEdit.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.page_edit)
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.save = QtWidgets.QPushButton(self.widget)
        self.save.setObjectName("save")
        self.gridLayout_5.addWidget(self.save, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        self.toolBox.addItem(self.page_edit, "")
        self.gridLayout.addWidget(self.toolBox, 0, 1, 1, 1)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 26))
        self.menubar.setObjectName("menubar")
        self.New = QtWidgets.QMenu(self.menubar)
        self.New.setObjectName("New")
        self.tool = QtWidgets.QMenu(self.menubar)
        self.tool.setObjectName("tool")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.addNoteBook = QtWidgets.QAction(Main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("F:/Picture/ico库/笔记本.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addNoteBook.setIcon(icon1)
        self.addNoteBook.setObjectName("addNoteBook")
        self.addBlock = QtWidgets.QAction(Main)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resource/文件.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBlock.setIcon(icon2)
        self.addBlock.setObjectName("addBlock")
        self.addPage = QtWidgets.QAction(Main)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resource/页面管理.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addPage.setIcon(icon3)
        self.addPage.setObjectName("addPage")
        self.set_tool = QtWidgets.QAction(Main)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resource/设置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.set_tool.setIcon(icon4)
        self.set_tool.setObjectName("set_tool")
        self.check = QtWidgets.QAction(Main)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resource/查看.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check.setIcon(icon5)
        self.check.setObjectName("check")
        self.log = QtWidgets.QAction(Main)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resource/日志.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log.setIcon(icon6)
        self.log.setObjectName("log")
        self.welcome = QtWidgets.QAction(Main)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resource/应用欢迎.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.welcome.setIcon(icon7)
        self.welcome.setObjectName("welcome")
        self.about = QtWidgets.QAction(Main)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resource/关于.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about.setIcon(icon8)
        self.about.setObjectName("about")
        self.actionimport_data = QtWidgets.QAction(Main)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resource/导入.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionimport_data.setIcon(icon9)
        self.actionimport_data.setObjectName("actionimport_data")
        self.actionoutput_data = QtWidgets.QAction(Main)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resource/导出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionoutput_data.setIcon(icon10)
        self.actionoutput_data.setObjectName("actionoutput_data")
        self.New.addAction(self.addNoteBook)
        self.New.addAction(self.addBlock)
        self.New.addAction(self.addPage)
        self.New.addSeparator()
        self.tool.addAction(self.set_tool)
        self.tool.addAction(self.about)
        self.file.addAction(self.check)
        self.file.addAction(self.welcome)
        self.file.addAction(self.log)
        self.file.addSeparator()
        self.file.addAction(self.actionimport_data)
        self.file.addAction(self.actionoutput_data)
        self.menubar.addAction(self.New.menuAction())
        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.tool.menuAction())

        self.retranslateUi(Main)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "简Note"))
        self.tree.headerItem().setText(0, _translate("Main", "笔记本"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_view), _translate("Main", "浏览"))
        self.save.setText(_translate("Main", "保存(Ctrl+S)"))
        self.save.setShortcut(_translate("Main", "Ctrl+S"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_edit), _translate("Main", "编辑"))
        self.New.setTitle(_translate("Main", "新建"))
        self.tool.setTitle(_translate("Main", "工具"))
        self.file.setTitle(_translate("Main", "文件"))
        self.addNoteBook.setText(_translate("Main", "笔记本"))
        self.addNoteBook.setShortcut(_translate("Main", "Ctrl+N"))
        self.addBlock.setText(_translate("Main", "分区"))
        self.addBlock.setShortcut(_translate("Main", "Ctrl+B"))
        self.addPage.setText(_translate("Main", "页"))
        self.addPage.setShortcut(_translate("Main", "Ctrl+P"))
        self.set_tool.setText(_translate("Main", "设置"))
        self.set_tool.setShortcut(_translate("Main", "Ctrl+Shift+S"))
        self.check.setText(_translate("Main", "查看"))
        self.check.setShortcut(_translate("Main", "Ctrl+C"))
        self.log.setText(_translate("Main", "日志"))
        self.log.setShortcut(_translate("Main", "Ctrl+L"))
        self.welcome.setText(_translate("Main", "欢迎界面"))
        self.welcome.setShortcut(_translate("Main", "Ctrl+W"))
        self.about.setText(_translate("Main", "关于"))
        self.about.setShortcut(_translate("Main", "Ctrl+A"))
        self.actionimport_data.setText(_translate("Main", "导入"))
        self.actionimport_data.setShortcut(_translate("Main", "Ctrl+I"))
        self.actionoutput_data.setText(_translate("Main", "导出"))
        self.actionoutput_data.setShortcut(_translate("Main", "Ctrl+O"))
